CREATE TABLE IF NOT EXISTS public.monitoring_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    soil_moisture DOUBLE PRECISION NOT NULL
        CHECK (soil_moisture >= 0 AND soil_moisture <= 100),
    water_level DOUBLE PRECISION NOT NULL
        CHECK (water_level >= 0),
    temperature DOUBLE PRECISION,
    humidity DOUBLE PRECISION
        CHECK (humidity IS NULL OR (humidity >= 0 AND humidity <= 100)),
    rain_probability DOUBLE PRECISION
        CHECK (
            rain_probability IS NULL
            OR (rain_probability >= 0 AND rain_probability <= 100)
        ),
    risk_level TEXT NOT NULL DEFAULT 'normal'
        CHECK (risk_level IN ('normal', 'medium', 'high', 'critical')),
    llm_explanation TEXT,
    recommendation TEXT,
    alert_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.monitoring_data ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.monitoring_data IS
    'Sensor readings with optional weather, LLM and alert information.';
