-- Data ownership:
-- monitoring_data.soil_moisture and water_level come from physical sensors.
-- weather_data fields come from the Open-Meteo API.
-- drought_assessments stores the backend score and Gemini explanation.

CREATE TABLE IF NOT EXISTS public.weather_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitoring_id BIGINT NOT NULL
        REFERENCES public.monitoring_data(id) ON DELETE CASCADE,
    source TEXT NOT NULL DEFAULT 'open-meteo'
        CHECK (source = 'open-meteo'),
    latitude DOUBLE PRECISION NOT NULL
        CHECK (latitude >= -90 AND latitude <= 90),
    longitude DOUBLE PRECISION NOT NULL
        CHECK (longitude >= -180 AND longitude <= 180),
    observed_at TIMESTAMPTZ NOT NULL,
    temperature_c DOUBLE PRECISION NOT NULL,
    humidity_percent DOUBLE PRECISION NOT NULL
        CHECK (humidity_percent >= 0 AND humidity_percent <= 100),
    precipitation_mm DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (precipitation_mm >= 0),
    recent_precipitation_7d_mm DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (recent_precipitation_7d_mm >= 0),
    forecast_precipitation_3d_mm DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (forecast_precipitation_3d_mm >= 0),
    forecast_precipitation_7d_mm DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (forecast_precipitation_7d_mm >= 0),
    evapotranspiration_mm DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (evapotranspiration_mm >= 0),
    forecast_evapotranspiration_7d_mm DOUBLE PRECISION NOT NULL DEFAULT 0
        CHECK (forecast_evapotranspiration_7d_mm >= 0),
    forecast_temperature_max_3d_c DOUBLE PRECISION NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.drought_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitoring_id BIGINT NOT NULL
        REFERENCES public.monitoring_data(id) ON DELETE CASCADE,
    weather_id BIGINT NOT NULL
        REFERENCES public.weather_data(id) ON DELETE CASCADE,
    risk_score DOUBLE PRECISION NOT NULL
        CHECK (risk_score >= 0 AND risk_score <= 100),
    risk_level TEXT NOT NULL
        CHECK (risk_level IN ('normal', 'medium', 'high', 'critical')),
    risk_factors JSONB NOT NULL DEFAULT '{}'::JSONB,
    analysis_source TEXT NOT NULL DEFAULT 'gemini-2.5-flash-lite',
    summary TEXT NOT NULL,
    drivers JSONB NOT NULL DEFAULT '[]'::JSONB,
    recommendations JSONB NOT NULL DEFAULT '[]'::JSONB,
    confidence TEXT NOT NULL
        CHECK (confidence IN ('low', 'medium', 'high')),
    requires_immediate_action BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.weather_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drought_assessments ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS weather_data_monitoring_id_idx
    ON public.weather_data (monitoring_id);

CREATE INDEX IF NOT EXISTS weather_data_observed_at_idx
    ON public.weather_data (observed_at DESC);

CREATE INDEX IF NOT EXISTS drought_assessments_monitoring_id_idx
    ON public.drought_assessments (monitoring_id);

CREATE INDEX IF NOT EXISTS drought_assessments_created_at_idx
    ON public.drought_assessments (created_at DESC);

CREATE INDEX IF NOT EXISTS drought_assessments_risk_level_idx
    ON public.drought_assessments (risk_level);

COMMENT ON COLUMN public.monitoring_data.soil_moisture IS
    'Physical soil-moisture sensor reading in percent.';
COMMENT ON COLUMN public.monitoring_data.water_level IS
    'Physical water-level sensor reading in the calibrated device unit.';
COMMENT ON TABLE public.weather_data IS
    'Current, recent and forecast weather obtained from Open-Meteo.';
COMMENT ON TABLE public.drought_assessments IS
    'Auditable drought score plus Gemini explanation and recommendations.';
