-- Support the detailed status types and LED colour emitted by the real sketch.

ALTER TABLE public.monitoring_data
    ADD COLUMN IF NOT EXISTS led_color TEXT;

ALTER TABLE public.monitoring_data
    DROP CONSTRAINT IF EXISTS monitoring_data_message_type_check;

ALTER TABLE public.monitoring_data
    ADD CONSTRAINT monitoring_data_message_type_check
    CHECK (
        message_type IN (
            'data',
            'alert',
            'alert_hardware_or_flood',
            'warning_dry',
            'data_wet',
            'data_ideal',
            'warning_dry_medium_water',
            'data_wet_medium_water',
            'data_medium',
            'alert_critical_dry_no_water',
            'warning_low_water_wet_soil',
            'warning_low_water'
        )
    );

COMMENT ON COLUMN public.monitoring_data.message_type IS
    'Detailed state generated by the ESP32 sensor decision rules.';
COMMENT ON COLUMN public.monitoring_data.led_color IS
    'English RGB LED colour name reported by the ESP32.';
